version: "3.8"

services:
  stark-invoice-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stark-invoice-container
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - stark-invoice-network

  # Optional: Add a development service
  stark-invoice-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: stark-invoice-dev-container
    ports:
      - "3001:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: unless-stopped
    networks:
      - stark-invoice-network
    profiles:
      - dev

networks:
  stark-invoice-network:
    driver: bridge

volumes:
  node_modules:
